index.html
public/js/assign-pathway.component.js
public/js/presenter.js
public/js/viewer.js

Status: Ready for review
Trello: https://trello.com/c/SYHK5cHv/11-ability-to-toggle-between-different-pathways-set-of-edges
- When the gluconeogenesis and glycolysis buttons are clicked, the current edges are removed before the new pathways are called.
- Corrected spelling of fructose 1,6-bisphosphate (added an 's')
-

Differet pathways

---

index.html
package-lock.json
package.json
public/js/drag-rotate-component.js
public/js/pathway_zoom.component.js
public/js/presenter.js
public/js/viewer.js

there is a camera attached per edge. You initially start in the main camera when running the program. When you click on an edge you will first be animated in the main camera's rig towards the edge after which the main camera will be disabled and you will be transferred into the edge's camera. Once you click the event plane(currently pink) you will switch back into the main camera which begins the zoom animation back out to your original position and rotation.
Trello: **https://trello.com/c/eBZmybLh**
- implemented a zoom in component to zoom into the edges.
- switch to multipleCamera-zoom branch and run the node on server.js
- Click any edge to zoom into the edge. You will know you are zoomed in when your screen changes to a pink color( this 
pink plane lies …

zoom component

---

public/js/viewer.js

Cleaned up code & fix typo
Status: **Don't forget to label this PR as either: Open for visibility or Ready for review!**
Trello: **(link to Trello card if applicable)**
- (change1)
- (link1)

Fix typo in Node constructor

---

public/js/viewer.js

Set up nodes + edges for placeholders
Trello: **https://trello.com/c/e5RC12pR/43-setting-up-placeholder-node-usage-in-viewer-network-description**
- (change1)
- View T-shaped reaction w/ placeholder node as described in the linked [trello ticket](https://trello.com/c/e5RC12pR/43-setting-up-placeholder-node-usage-in-viewer-network-description)
- (link1)

Set up placeholder node + edges

---

index.html
public/js/pathway_zoom.component.js

I moved the camera back such that the whole network is visible to your window
Status:  Ready for review!
Trello: [trello.com/c/ZTZGjXH5](url)
- Within index.html, I changed the position of the camera-rig from (1,-1.2,5) to (1,0,11)
-Within pathway_zoom.component.js I added a new schema var titled, initPos which holds the position (1,0,11) and set the respected animation to reference that new variable

Updated camera position

---

public/js/highlight-sequence.js
public/js/viewer.js

Add ability to highlihgt edges
Status: ** Ready for review!**
Trello: **https://trello.com/c/3x4BbHlA/52-write-component-that-uses-a-list-of-edges-to-iterate-over-aframe-elements-and-change-visuals**
- Refactored `highlight-changes.js`
- Fixed issue where T-shaped reaction wasn't highlighted properly by adding the placeholder node to `sequences.nodes` array
- Test that highlighting sequences works properly
- Add edges to `sequences.edges` array in `viewer.js`, verify that edges and nodes are highlighted properly
- (link1)

Highlight edges

---

index.html
public/js/viewer.js

Trello: 
- https://trello.com/c/qmXG178k
- https://trello.com/c/KhQDxbrY
- Added 7 new pathways
- reorganized the GUI buttons
- Added new nodes into the network
- Added new A-Frame buttons to switch between pathways
- There seems to be a bug when zooming out of an edge. It seems the event planes in the pathway_zoom.component.js are only initialized when All pathways, gluconeogenesis, or glycolysis pathways are shown

Updated pathways

---

public/js/pathway_zoom.component.js
public/js/presenter.js
public/js/viewer.js

Trello: **https://trello.com/c/oU2Uu0N7**
- fixed selector for edge cameras on ``DrawEdges`` that wasnt deleting them on pathway switch
- fixed selector in animation complete event handlers because for some reason the cameras werent getting their ids assigned

fixed camera bug

---

public/js/pathway_zoom.component.js
public/js/presenter.js

Trello: **https://trello.com/c/oU2Uu0N7**
- added remove fxn and helper to remove handlers to ``presenter.js``
- added call to removeAttribute to edge deletion in update in ``presenter.js``

animationcomplete events listeners removed on removing pathway_zoom component

---

public/js/highlight-sequence.js

Trello: **https://trello.com/c/nju2UDBh/58-highlight-coloring-and-shading**
- Added functionality to dynamically add outlines to the scene
- (link1)

Outline elements

---

index.html
public/js/highlight-behavior.component.js
public/js/highlight-button-behavior.component.js
public/js/presenter.js
public/js/viewer.js

original attempt with minimal design was functional but didn't have the desired behavior. more complex components for edge and button highlighting are implemented here and also changes from drop-down-menu are being piggybacked.

state machines for edge and button behavior

---

index.html
public/js/highlight-behavior.component.js
public/js/highlight-button-behavior.component.js
public/js/highlight-sequence.js
public/js/presenter.js
public/js/viewer.js

#Button States for hover and outline
Trello: **https://trello.com/c/Sn4EzQmk/65-button-states-for-hover-and-outline**
- Added toggling effects to the GUI buttons for highlighting and outlining
- Will need more investigation into the `border-color` and `font-color` attributes from https://github.com/rdub80/aframe-gui, they're not working as expected
- Note that there are edge cases with selecting/de-selecting different pathways. Not sure how best to handle these cases, since the structure is changing when different buttons are clicked
- (link1)

Button states

---

public/js/animation-behavior.component.js
public/js/toggle-button.component.js

Status: ** Ready for review!**
Trello: **https://trello.com/c/TLCbRRnH**
-  animation-behavior.component.js -> implemented animate() and stopAnimation() which are used to change the active variable in displace.shader.js 
- I tested the functionality by appending animation-behavior on an edge and calling animate() and stopAnimation() with a GUI button.
- (link1)

Animation call

---

index.html
public/js/animation-behavior.component.js
public/js/animation-button.component.js

Trello: **https://trello.com/c/3XPiZe8g/76-animation-button-click-listener**
- Added clickListener to animation buttons for toggling animations
- (link1)

Button listener

---

index.html
public/js/label-behavior.component.js
public/js/presenter.js

Trello: **(link to Trello card if applicable)**
- extracted labeling feature from presenter.js and created a new component titled "label-behavior.component.js" with behavioral functionality
- (link1)

Toggle labels

---

index.html
public/js/NodePresenter.js
public/js/network-view.component.js
public/js/toggle-label.js

Trello: **https://trello.com/c/Xb0VnBSG**
- Separated the node initialization from network-view.component.js into NodePresenter.js
- run as usual.
- (link1)

Node presenter

---

index.html
public/js/UIPresenter.js
public/js/network-view.component.js
public/js/toggle-label.js

#The UI is dynamically created
Status: **Open for visibility**
Trello: **https://trello.com/c/iMZ21k6w**
- created a new file called UIPresenter.js
-recreated the UI menu in that new file
- fix flex containers arrangement
- make the animation menu work for all pathways

Ui presenter

---

index.html
public/js/network-view.component.js
public/js/reset-camera-behavior.component.js

Trello: **https://trello.com/c/UJkisrUx**
- Added two helpers in network-view.component.js
- Created reset-camera-behavior.component.js
- Added a reset button in index.html
- Click "reset camera" button in menu

Camera reset

---

public/js/highlight-behavior.component.js
public/js/toggle-label.js

Trello: **https://trello.com/c/r42os7Ws/93-add-call-to-highlight-labels-button-from-highlight-button**
- (change1)
- (link1)

Highlight label toggle

---

index.html
public/js/NodePresenter.js
public/js/highlight-behavior.component.js
public/js/node-animation.component.js

Status: **Open for visibility or Ready for review!**
Trello: **https://trello.com/c/dAtwDT5k/94-create-node-animation-component**
- Added component to animate / change color of nodes
- (link1)

add node animation component

---

index.html
public/js/network-view.component.js
public/js/pathway-focus-behavior.component.js
public/js/pathway-menu.component.js

Trello: **https://trello.com/c/vQf5Ik3p/101-extend-uipresenter-for-pathway-menu**
- (change1)
- (link1)

Pathway menu

---

index.html
public/js/Model.js

Trello: **https://trello.com/c/zQhBG4nU/110-additional-nodes-edges-in-network**
- (change1)
- (link1)

Added new nodes in z-plane
